export const WORKOUT_TEMPLATES = [
  {
    id: 'push',
    name: 'Push',
    name_he: 'דחיפה',
    color: '#F97316',
    muscles: ['Chest', 'Triceps', 'Shoulders', 'Quads'],
    sort_order: 0,
    exercises: [
      {
        key: 'cable_tricep_kickback',
        name: 'פשיטת מרפק קיקבאק בפולי',
        name_en: 'Cable Tricep Kickback',
        videoId: 'okEf9-X_GvM',
        sets: 3,
        reps: '8-12',
        rest: 60,
        superset: null,
      },
      {
        key: 'overhead_cable_tricep',
        name: 'פשיטת מרפק עם חבל מאחורי הראש',
        name_en: 'Overhead Cable Tricep Extension',
        videoId: 'l4i7iDLiMXs',
        sets: 3,
        reps: '8-10',
        rest: 90,
        superset: null,
      },
      {
        key: 'incline_db_press',
        name: 'לחיצת חזה עליון עם משקולות',
        name_en: 'Incline Dumbbell Press',
        videoId: 'oZVCBM9f8Eo',
        sets: 3,
        reps: '6-8',
        rest: 120,
        superset: null,
      },
      {
        key: 'machine_fly_roller',
        name: 'פרפר במכונה עם גליל',
        name_en: 'Machine Fly (Roller)',
        videoId: 'Dbly77Jgbo8',
        sets: 3,
        reps: '10-12',
        rest: 60,
        superset: null,
      },
      {
        key: 'smith_shoulder_press',
        name: 'לחיצת כתפיים בסמית׳',
        name_en: 'Smith Machine Shoulder Press',
        videoId: 'kYZ0aUEzgEQ',
        sets: 3,
        reps: '8-10',
        rest: 120,
        superset: null,
      },
      {
        key: 'cable_lateral_raise',
        name: 'הרחקת כתף בקרוס',
        name_en: 'Cable Lateral Raise',
        videoId: 'nMCQuV6HE3A',
        sets: 3,
        reps: '10-12',
        rest: 30,
        tempo: '1:2:3',
        superset: null,
      },
      {
        key: 'leg_press',
        name: 'לחיצת רגליים',
        name_en: 'Leg Press',
        videoId: 'nDh_BlnLCGc',
        sets: 3,
        reps: '8-10',
        rest: 120,
        tempo: '1:1:3',
        superset: null,
      },
      {
        key: 'calf_raise_leg_press',
        name: 'תאומים בלג פרס',
        name_en: 'Calf Raise on Leg Press',
        videoId: 'dhRz1Ns60Zg',
        sets: 3,
        reps: '8-12',
        rest: 60,
        superset: null,
      },
      {
        key: 'sissy_squat',
        name: 'סיסי סקוואט',
        name_en: 'Sissy Squat',
        videoId: 'VUiFlZ2FsKA',
        sets: 3,
        reps: 'Max',
        rest: 60,
        superset: null,
      },
    ],
  },
  {
    id: 'pull',
    name: 'Pull',
    name_he: 'משיכה',
    color: '#3B82F6',
    muscles: ['Back', 'Biceps', 'Hamstrings', 'Abs'],
    sort_order: 1,
    exercises: [
      {
        key: 'reverse_preacher_curl',
        name: 'פריצ׳ר הפוך',
        name_en: 'Reverse Preacher Curl',
        videoId: '8vzHHAJTndU',
        sets: 3,
        reps: '8-12',
        rest: 90,
        superset: null,
      },
      {
        key: 'barbell_curl',
        name: 'כפיפת מרפק עם מוט',
        name_en: 'Barbell Curl',
        videoId: 'QZEqB6wUPxQ',
        sets: 3,
        reps: '10-12',
        rest: 60,
        tempo: '1:2:3',
        superset: null,
      },
      {
        key: 'close_grip_lat_pulldown',
        name: 'משיכה בפולי אחיזה צרה',
        name_en: 'Close Grip Lat Pulldown',
        videoId: 'ecRF8ERf2q4',
        sets: 3,
        reps: '8-10',
        rest: 120,
        superset: null,
      },
      {
        key: 'machine_row',
        name: 'חתירה במכונה',
        name_en: 'Machine Row',
        videoId: 'TeFo51Q_Nsc',
        sets: 3,
        reps: '8-10',
        rest: 90,
        superset: null,
      },
      {
        key: 'cable_reverse_fly',
        name: 'הרחקה אופקית בקרוס',
        name_en: 'Cable Reverse Fly',
        videoId: 'CfLXDFh110w',
        sets: 3,
        reps: '12-15',
        rest: 60,
        superset: null,
      },
      {
        key: 'seated_leg_curl',
        name: 'כפיפת ברך בישיבה',
        name_en: 'Seated Leg Curl',
        videoId: 'PttfLAlB2aY',
        sets: 3,
        reps: '10-12',
        rest: 120,
        tempo: '1:1:3',
        superset: null,
      },
      {
        key: 'roman_chair_hamstring',
        name: 'כיסא רומי דגש להמסטרינג',
        name_en: 'Roman Chair (Hamstring)',
        videoId: 'HEglazwU9WU',
        sets: 3,
        reps: '10-12',
        rest: 120,
        superset: null,
      },
      {
        key: 'hanging_knee_raise',
        name: 'הרמות רגליים מקופלות',
        name_en: 'Hanging Knee Raise',
        videoId: 'X-ACS9vpRyU',
        sets: 3,
        reps: '6-12',
        rest: 60,
        superset: null,
      },
      {
        key: 'cable_crunch_kneeling',
        name: 'כפיפות בטן על הברכיים בפולי',
        name_en: 'Kneeling Cable Crunch',
        videoId: 'NJQROeaBiVE',
        sets: 3,
        reps: '12-15',
        rest: 60,
        superset: null,
      },
    ],
  },
  {
    id: 'upper',
    name: 'Upper',
    name_he: 'פלג גוף עליון',
    color: '#8B5CF6',
    muscles: ['Biceps', 'Triceps', 'Back', 'Chest', 'Shoulders'],
    sort_order: 2,
    exercises: [
      {
        key: 'reverse_preacher_curl',
        name: 'פריצ׳ר הפוך',
        name_en: 'Reverse Preacher Curl',
        videoId: '8vzHHAJTndU',
        sets: 3,
        reps: '8-12',
        superset: 'A',
      },
      {
        key: 'overhead_db_tricep',
        name: 'פשיטת מרפק מאחורי הראש עם משקולת',
        name_en: 'Overhead DB Tricep Extension',
        videoId: '-Vyt2QdsR7E',
        sets: 3,
        reps: '10-12',
        rest: 60,
        superset: 'A',
      },
      {
        key: 'cable_bar_curl',
        name: 'כפיפת מרפק בקרוס עם מוט',
        name_en: 'Cable Bar Curl',
        videoId: 'NFzTWp2qpiE',
        sets: 3,
        reps: '10-12',
        tempo: '1:2:3',
        superset: 'B',
      },
      {
        key: 'cable_bar_pushdown',
        name: 'פשיטת מרפק בקרוס עם מוט',
        name_en: 'Cable Bar Pushdown',
        videoId: '2-LAMcpzODU',
        sets: 3,
        reps: '10-12',
        rest: 60,
        superset: 'B',
      },
      {
        key: 'close_grip_lat_pulldown',
        name: 'משיכה בפולי אחיזה צרה',
        name_en: 'Close Grip Lat Pulldown',
        videoId: 'ecRF8ERf2q4',
        sets: 3,
        reps: '8-10',
        rest: 120,
        superset: null,
      },
      {
        key: 'incline_db_press',
        name: 'לחיצת חזה עליון עם משקולות',
        name_en: 'Incline Dumbbell Press',
        videoId: 'oZVCBM9f8Eo',
        sets: 3,
        reps: '6-8',
        rest: 120,
        superset: null,
      },
      {
        key: 'single_arm_reverse_fly',
        name: 'הרחקה אופקית - פרפר הפוך - יד יד',
        name_en: 'Single Arm Reverse Fly',
        videoId: 'GDEINoYs10U',
        sets: 3,
        reps: '8-12',
        superset: 'E',
      },
      {
        key: 'machine_fly',
        name: 'פרפר במכונה',
        name_en: 'Machine Fly',
        videoId: 'Z57CtFmRMxA',
        sets: 3,
        reps: '10-12',
        rest: 60,
        superset: 'E',
      },
      {
        key: 'machine_row',
        name: 'חתירה במכונה',
        name_en: 'Machine Row',
        videoId: 'TeFo51Q_Nsc',
        sets: 3,
        reps: '8-10',
        superset: 'F',
      },
      {
        key: 'db_lateral_raise',
        name: 'הרחקות כתפיים כנגד משקולות',
        name_en: 'DB Lateral Raise',
        videoId: 'WJm9zA2NY8E',
        sets: 3,
        reps: '10-12',
        rest: 60,
        superset: 'F',
      },
      {
        key: 'hanging_knee_raise',
        name: 'הרמות רגליים מקופלות',
        name_en: 'Hanging Knee Raise',
        videoId: 'X-ACS9vpRyU',
        sets: 3,
        reps: '6-12',
        rest: 60,
        superset: null,
      },
      {
        key: 'cable_crunch_kneeling',
        name: 'כפיפות בטן על הברכיים בפולי',
        name_en: 'Kneeling Cable Crunch',
        videoId: 'NJQROeaBiVE',
        sets: 3,
        reps: '12-15',
        rest: 60,
        superset: null,
      },
    ],
  },
  {
    id: 'lower',
    name: 'Lower Focused',
    name_he: 'פלג גוף תחתון',
    color: '#10B981',
    muscles: ['Quads', 'Hamstrings', 'Glutes', 'Calves'],
    sort_order: 3,
    exercises: [
      {
        key: 'seated_leg_curl',
        name: 'כפיפת ברך בישיבה',
        name_en: 'Seated Leg Curl',
        videoId: 'PttfLAlB2aY',
        sets: 3,
        reps: '10-12',
        rest: 90,
        tempo: '1:1:3',
        superset: null,
      },
      {
        key: 'seated_leg_extension',
        name: 'פשיטת ברך בישיבה',
        name_en: 'Seated Leg Extension',
        videoId: 'o90ocSBDJis',
        sets: 2,
        reps: '10-12',
        rest: 60,
        tempo: '1:2:3',
        superset: null,
      },
      {
        key: 'smith_squat',
        name: 'סקוואט בסמית׳',
        name_en: 'Smith Machine Squat',
        videoId: 'AHnX-aimA4E',
        sets: 3,
        reps: '8-10',
        rest: 120,
        superset: null,
      },
      {
        key: 'roman_chair_hamstring',
        name: 'כיסא רומי דגש להמסטרינג',
        name_en: 'Roman Chair (Hamstring)',
        videoId: 'HEglazwU9WU',
        sets: 3,
        reps: '8-10',
        rest: 120,
        superset: null,
      },
      {
        key: 'smith_calf_raise',
        name: 'עליות תאומים בסמית׳',
        name_en: 'Smith Machine Calf Raise',
        videoId: 'wlqTemUXPXY',
        sets: 3,
        reps: '8-12',
        rest: 60,
        superset: null,
      },
      {
        key: 'hip_adduction',
        name: 'קירוב ירך בישיבה',
        name_en: 'Hip Adduction',
        videoId: '0PPaAG3-v6U',
        sets: 2,
        reps: '10-12',
        rest: 90,
        superset: null,
      },
    ],
  },
]
