export const WORKOUT_TEMPLATES = [
  {
    id: 'push',
    name: 'Push',
    name_he: 'דחיפה',
    color: '#F97316',
    muscles: ['Chest', 'Triceps', 'Shoulders', 'Quads'],
    sort_order: 0,
    program: 'classic',
    exercises: [
      {
        key: 'cable_tricep_kickback',
        name: 'פשיטת מרפק קיקבאק בפולי',
        name_en: 'Cable Tricep Kickback',
        videoId: 'okEf9-X_GvM',
        sets: 3,
        reps: '8-12',
        rest: 60,
        superset: null,
      },
      {
        key: 'overhead_cable_tricep',
        name: 'פשיטת מרפק עם חבל מאחורי הראש',
        name_en: 'Overhead Cable Tricep Extension',
        videoId: 'l4i7iDLiMXs',
        sets: 3,
        reps: '8-10',
        rest: 90,
        superset: null,
      },
      {
        key: 'incline_db_press',
        name: 'לחיצת חזה עליון עם משקולות',
        name_en: 'Incline Dumbbell Press',
        videoId: 'oZVCBM9f8Eo',
        sets: 3,
        reps: '6-8',
        rest: 120,
        superset: null,
      },
      {
        key: 'machine_fly_roller',
        name: 'פרפר במכונה עם גליל',
        name_en: 'Machine Fly (Roller)',
        videoId: 'Dbly77Jgbo8',
        sets: 3,
        reps: '10-12',
        rest: 60,
        superset: null,
      },
      {
        key: 'smith_shoulder_press',
        name: 'לחיצת כתפיים בסמית׳',
        name_en: 'Smith Machine Shoulder Press',
        videoId: 'kYZ0aUEzgEQ',
        sets: 3,
        reps: '8-10',
        rest: 120,
        superset: null,
      },
      {
        key: 'cable_lateral_raise',
        name: 'הרחקת כתף בקרוס',
        name_en: 'Cable Lateral Raise',
        videoId: 'nMCQuV6HE3A',
        sets: 3,
        reps: '10-12',
        rest: 30,
        tempo: '1:2:3',
        superset: null,
      },
      {
        key: 'leg_press',
        name: 'לחיצת רגליים',
        name_en: 'Leg Press',
        videoId: 'nDh_BlnLCGc',
        sets: 3,
        reps: '8-10',
        rest: 120,
        tempo: '1:1:3',
        superset: null,
      },
      {
        key: 'calf_raise_leg_press',
        name: 'תאומים בלג פרס',
        name_en: 'Calf Raise on Leg Press',
        videoId: 'dhRz1Ns60Zg',
        sets: 3,
        reps: '8-12',
        rest: 60,
        superset: null,
      },
      {
        key: 'sissy_squat',
        name: 'סיסי סקוואט',
        name_en: 'Sissy Squat',
        videoId: 'VUiFlZ2FsKA',
        sets: 3,
        reps: 'Max',
        rest: 60,
        superset: null,
      },
    ],
  },
  {
    id: 'pull',
    name: 'Pull',
    name_he: 'משיכה',
    color: '#3B82F6',
    muscles: ['Back', 'Biceps', 'Hamstrings', 'Abs'],
    sort_order: 1,
    program: 'classic',
    exercises: [
      {
        key: 'reverse_preacher_curl',
        name: 'פריצ׳ר הפוך',
        name_en: 'Reverse Preacher Curl',
        videoId: '8vzHHAJTndU',
        sets: 3,
        reps: '8-12',
        rest: 90,
        superset: null,
      },
      {
        key: 'barbell_curl',
        name: 'כפיפת מרפק עם מוט',
        name_en: 'Barbell Curl',
        videoId: 'QZEqB6wUPxQ',
        sets: 3,
        reps: '10-12',
        rest: 60,
        tempo: '1:2:3',
        superset: null,
      },
      {
        key: 'close_grip_lat_pulldown',
        name: 'משיכה בפולי אחיזה צרה',
        name_en: 'Close Grip Lat Pulldown',
        videoId: 'ecRF8ERf2q4',
        sets: 3,
        reps: '8-10',
        rest: 120,
        superset: null,
      },
      {
        key: 'machine_row',
        name: 'חתירה במכונה',
        name_en: 'Machine Row',
        videoId: 'TeFo51Q_Nsc',
        sets: 3,
        reps: '8-10',
        rest: 90,
        superset: null,
      },
      {
        key: 'cable_reverse_fly',
        name: 'הרחקה אופקית בקרוס',
        name_en: 'Cable Reverse Fly',
        videoId: 'CfLXDFh110w',
        sets: 3,
        reps: '12-15',
        rest: 60,
        superset: null,
      },
      {
        key: 'seated_leg_curl',
        name: 'כפיפת ברך בישיבה',
        name_en: 'Seated Leg Curl',
        videoId: 'PttfLAlB2aY',
        sets: 3,
        reps: '10-12',
        rest: 120,
        tempo: '1:1:3',
        superset: null,
      },
      {
        key: 'roman_chair_hamstring',
        name: 'כיסא רומי דגש להמסטרינג',
        name_en: 'Roman Chair (Hamstring)',
        videoId: 'HEglazwU9WU',
        sets: 3,
        reps: '10-12',
        rest: 120,
        superset: null,
      },
      {
        key: 'hanging_knee_raise',
        name: 'הרמות רגליים מקופלות',
        name_en: 'Hanging Knee Raise',
        videoId: 'X-ACS9vpRyU',
        sets: 3,
        reps: '6-12',
        rest: 60,
        superset: null,
      },
      {
        key: 'cable_crunch_kneeling',
        name: 'כפיפות בטן על הברכיים בפולי',
        name_en: 'Kneeling Cable Crunch',
        videoId: 'NJQROeaBiVE',
        sets: 3,
        reps: '12-15',
        rest: 60,
        superset: null,
      },
    ],
  },
  {
    id: 'upper',
    name: 'Upper',
    name_he: 'פלג גוף עליון',
    color: '#8B5CF6',
    muscles: ['Biceps', 'Triceps', 'Back', 'Chest', 'Shoulders'],
    sort_order: 2,
    program: 'classic',
    exercises: [
      {
        key: 'reverse_preacher_curl',
        name: 'פריצ׳ר הפוך',
        name_en: 'Reverse Preacher Curl',
        videoId: '8vzHHAJTndU',
        sets: 3,
        reps: '8-12',
        superset: 'A',
      },
      {
        key: 'overhead_db_tricep',
        name: 'פשיטת מרפק מאחורי הראש עם משקולת',
        name_en: 'Overhead DB Tricep Extension',
        videoId: '-Vyt2QdsR7E',
        sets: 3,
        reps: '10-12',
        rest: 60,
        superset: 'A',
      },
      {
        key: 'cable_bar_curl',
        name: 'כפיפת מרפק בקרוס עם מוט',
        name_en: 'Cable Bar Curl',
        videoId: 'NFzTWp2qpiE',
        sets: 3,
        reps: '10-12',
        tempo: '1:2:3',
        superset: 'B',
      },
      {
        key: 'cable_bar_pushdown',
        name: 'פשיטת מרפק בקרוס עם מוט',
        name_en: 'Cable Bar Pushdown',
        videoId: '2-LAMcpzODU',
        sets: 3,
        reps: '10-12',
        rest: 60,
        superset: 'B',
      },
      {
        key: 'close_grip_lat_pulldown',
        name: 'משיכה בפולי אחיזה צרה',
        name_en: 'Close Grip Lat Pulldown',
        videoId: 'ecRF8ERf2q4',
        sets: 3,
        reps: '8-10',
        rest: 120,
        superset: null,
      },
      {
        key: 'incline_db_press',
        name: 'לחיצת חזה עליון עם משקולות',
        name_en: 'Incline Dumbbell Press',
        videoId: 'oZVCBM9f8Eo',
        sets: 3,
        reps: '6-8',
        rest: 120,
        superset: null,
      },
      {
        key: 'single_arm_reverse_fly',
        name: 'הרחקה אופקית - פרפר הפוך - יד יד',
        name_en: 'Single Arm Reverse Fly',
        videoId: 'GDEINoYs10U',
        sets: 3,
        reps: '8-12',
        superset: 'E',
      },
      {
        key: 'machine_fly',
        name: 'פרפר במכונה',
        name_en: 'Machine Fly',
        videoId: 'Z57CtFmRMxA',
        sets: 3,
        reps: '10-12',
        rest: 60,
        superset: 'E',
      },
      {
        key: 'machine_row',
        name: 'חתירה במכונה',
        name_en: 'Machine Row',
        videoId: 'TeFo51Q_Nsc',
        sets: 3,
        reps: '8-10',
        superset: 'F',
      },
      {
        key: 'db_lateral_raise',
        name: 'הרחקות כתפיים כנגד משקולות',
        name_en: 'DB Lateral Raise',
        videoId: 'WJm9zA2NY8E',
        sets: 3,
        reps: '10-12',
        rest: 60,
        superset: 'F',
      },
      {
        key: 'hanging_knee_raise',
        name: 'הרמות רגליים מקופלות',
        name_en: 'Hanging Knee Raise',
        videoId: 'X-ACS9vpRyU',
        sets: 3,
        reps: '6-12',
        rest: 60,
        superset: null,
      },
      {
        key: 'cable_crunch_kneeling',
        name: 'כפיפות בטן על הברכיים בפולי',
        name_en: 'Kneeling Cable Crunch',
        videoId: 'NJQROeaBiVE',
        sets: 3,
        reps: '12-15',
        rest: 60,
        superset: null,
      },
    ],
  },
  {
    id: 'lower',
    name: 'Lower Focused',
    name_he: 'פלג גוף תחתון',
    color: '#10B981',
    muscles: ['Quads', 'Hamstrings', 'Glutes', 'Calves'],
    sort_order: 3,
    program: 'classic',
    exercises: [
      {
        key: 'seated_leg_curl',
        name: 'כפיפת ברך בישיבה',
        name_en: 'Seated Leg Curl',
        videoId: 'PttfLAlB2aY',
        sets: 3,
        reps: '10-12',
        rest: 90,
        tempo: '1:1:3',
        superset: null,
      },
      {
        key: 'seated_leg_extension',
        name: 'פשיטת ברך בישיבה',
        name_en: 'Seated Leg Extension',
        videoId: 'o90ocSBDJis',
        sets: 2,
        reps: '10-12',
        rest: 60,
        tempo: '1:2:3',
        superset: null,
      },
      {
        key: 'smith_squat',
        name: 'סקוואט בסמית׳',
        name_en: 'Smith Machine Squat',
        videoId: 'AHnX-aimA4E',
        sets: 3,
        reps: '8-10',
        rest: 120,
        superset: null,
      },
      {
        key: 'roman_chair_hamstring',
        name: 'כיסא רומי דגש להמסטרינג',
        name_en: 'Roman Chair (Hamstring)',
        videoId: 'HEglazwU9WU',
        sets: 3,
        reps: '8-10',
        rest: 120,
        superset: null,
      },
      {
        key: 'smith_calf_raise',
        name: 'עליות תאומים בסמית׳',
        name_en: 'Smith Machine Calf Raise',
        videoId: 'wlqTemUXPXY',
        sets: 3,
        reps: '8-12',
        rest: 60,
        superset: null,
      },
      {
        key: 'hip_adduction',
        name: 'קירוב ירך בישיבה',
        name_en: 'Hip Adduction',
        videoId: '0PPaAG3-v6U',
        sets: 2,
        reps: '10-12',
        rest: 90,
        superset: null,
      },
    ],
  },

  // ─── ABC Recomp Program ───────────────────────────────────────────────────

  {
    id: 'abc_upper',
    name: 'Upper',
    name_he: 'פלג גוף עליון',
    color: '#3B82F6',
    muscles: ['Chest', 'Back', 'Shoulders', 'Triceps', 'Biceps'],
    sort_order: 4,
    program: 'abc_recomp',
    exercises: [
      // Chest
      {
        key: 'smith_incline_press',
        name: 'חזה עליון בסמית׳',
        name_en: 'Smith Machine Incline Press',
        videoId: 'tLB1XtM21Fk',
        sets: 3,
        reps: '6-8',
        rest: 120,
        superset: null,
        notes_he: 'הביא את המוט עד נגיעה מלאה בחזה לעשות עצירה של 2 שניות ואז לדחוף.',
        notes: 'Bring the bar down to full chest touch, pause for 2 seconds at the bottom, then press up.',
      },
      {
        key: 'machine_chest_press',
        name: 'לחיצת חזה במכונה',
        name_en: 'Machine Chest Press',
        videoId: 'zgP-UCKGe24',
        sets: 2,
        reps: '8-12',
        rest: 120,
        superset: null,
        notes_he: 'לשמור על מרפקים בקו כתף - לקחת כל סט קרוב לכשל.',
        notes: 'Keep elbows in line with shoulders. Take each set close to failure.',
      },
      {
        key: 'machine_fly_roller',
        name: 'פרפר במכונה עם גליל',
        name_en: 'Machine Fly (Roller)',
        videoId: 'JYmszQs-mRs',
        sets: 2,
        reps: '12-15',
        rest: 60,
        superset: null,
        notes_he: 'לשמור על השכמות והטרפזים על המשענת של הכסא או על הגליל.',
        notes: 'Keep scapulae and traps pressed against the pad/roller throughout the movement.',
      },
      // Back
      {
        key: 'wide_grip_lat_pulldown',
        name: 'משיכה בפולי אחיזה רחבה',
        name_en: 'Wide Grip Lat Pulldown',
        videoId: '7JnP8dFbS14',
        sets: 3,
        reps: '8-10',
        rest: 120,
        superset: null,
        notes_he: 'לשבת הכי צמוד לכיסא, ישבן עד הסוף לפנים, להשען אחורה 10 מעלות.',
        notes: 'Sit as close to the pad as possible, glutes all the way forward on the seat, lean back approximately 10 degrees.',
      },
      {
        key: 'single_arm_cable_row',
        name: 'חתירה יד אחת בפולי',
        name_en: 'Single Arm Cable Row',
        videoId: 'CrylzZHfO1c',
        sets: 3,
        reps: '8-10',
        rest: 60,
        superset: null,
        notes_he: 'הדגש הכי חשוב זה לשמור שלא תהיה כפיפה של יותר מ-90 מעלות.',
        notes: 'The key focus is to maintain no more than 90 degrees of elbow bend.',
      },
      // Shoulders superset F
      {
        key: 'seated_face_pull',
        name: 'פייס פול בישיבה',
        name_en: 'Seated Face Pull',
        videoId: '4UhV4cCkugM',
        sets: 3,
        reps: '12-15',
        superset: 'F',
      },
      {
        key: 'db_lateral_raise',
        name: 'הרחקות כתפיים כנגד משקולות',
        name_en: 'DB Lateral Raises',
        videoId: 'XPPfnSEATJA',
        sets: 3,
        reps: '12-15',
        rest: 60,
        superset: 'F',
        notes_he: 'להרכין עוד קצת קדימה.',
        notes: 'Lean slightly forward.',
      },
      // Triceps
      {
        key: 'single_arm_tricep_pushdown',
        name: 'פשיטת מרפק יד אחת אקצנטרי',
        name_en: 'Single Arm Eccentric Tricep Pushdown',
        videoId: '0CeC53ruBdU',
        sets: 2,
        reps: '10+5',
        rest: 60,
        superset: null,
        notes_he: 'לבצע כפיפת מרפק רגילה עם יד אחת ברגע שמגיעים לכשל להיעזר עם היד השנייה ל-5 חזרות נוספות עם דגש על האקצנטרי.',
        notes: 'Perform regular single-arm pushdowns; when reaching failure, assist with the other hand for 5 additional eccentric-focused reps.',
      },
      {
        key: 'overhead_cable_tricep',
        name: 'פשיטת מרפק עם חבל מאחורי הראש',
        name_en: 'Overhead Cable Tricep Extension',
        videoId: 'l4i7iDLiMXs',
        sets: 3,
        reps: '8-10',
        rest: 90,
        superset: null,
        notes_he: 'לקחת רגל חזקה קדימה, ולנסות להצמיד מרפקים כמה שאפשר.',
        notes: 'Step forward with one strong leg, keep elbows as close together as possible.',
      },
      // Biceps
      {
        key: 'single_arm_preacher_curl',
        name: 'פריצ׳ר יד אחת',
        name_en: 'Single Arm Preacher Curl',
        videoId: '2hmQRh6ZF4o',
        sets: 2,
        reps: '12',
        rest: 30,
        superset: null,
        notes_he: 'אפשר להיעזר ביד השנייה כדי להגיע ל-12 חזרות, להניח את הזרוע על הכרית.',
        notes: 'Can assist with the other hand to reach 12 reps. Rest the arm fully on the preacher pad.',
      },
      {
        key: 'cable_bar_curl',
        name: 'כפיפת מרפק בקרוס עם מוט',
        name_en: 'Cable Bar Curl',
        videoId: 'k_oxpDonR8s',
        sets: 2,
        reps: '12-15',
        rest: 60,
        tempo: '1:2:3',
        superset: null,
        notes_he: 'להניח את המרפקים על הצלעות ולהוריד את הכתפיים (והשכמות) למטה לאורך כל התנועה.',
        notes: 'Place elbows against ribs, pull shoulders (and scapulae) down throughout.',
      },
    ],
  },
  {
    id: 'abc_lower',
    name: 'Lower',
    name_he: 'פלג גוף תחתון',
    color: '#10B981',
    muscles: ['Hamstrings', 'Quads', 'Calves', 'Abs'],
    sort_order: 5,
    program: 'abc_recomp',
    exercises: [
      // Legs
      {
        key: 'roman_chair_hamstring',
        name: 'כיסא רומי דגש להמסטרינג',
        name_en: 'Roman Chair (Hamstring Focus)',
        videoId: 'LlXMq-Lrc-U',
        sets: 3,
        reps: '8-12',
        rest: 120,
        superset: null,
        notes_he: 'לשמור על גב מעוגל, לרדת ממש נמוך שהראש כמעט יגע ברצפה.',
        notes: 'Maintain a rounded back, go very low so the head almost touches the floor.',
      },
      {
        key: 'leg_press',
        name: 'לחיצת רגליים',
        name_en: 'Leg Press',
        videoId: 'CHPHn-OnTqE',
        sets: 2,
        reps: '8-10',
        rest: 120,
        tempo: '1:1:3',
        superset: null,
        notes_he: 'לשים לב לתנועה איטית בירידה ולטווח תנועה כפי שמודגם בסרטון.',
        notes: 'Focus on slow eccentric (lowering) and full range of motion as demonstrated in the video.',
      },
      // Quads/Hamstrings superset C
      {
        key: 'sissy_squat',
        name: 'סיסי סקוואט',
        name_en: 'Sissy Squat',
        videoId: 'VUiFlZ2FsKA',
        sets: 3,
        reps: 'Max',
        superset: 'C',
        notes_he: 'לשמור על ישבן מכווץ חזק לאורך כל התנועה, להיעזר עם יד אחת לשיווי משקל.',
        notes: 'Keep glutes squeezed tight throughout the entire movement. Can assist with one hand for balance.',
      },
      {
        key: 'seated_leg_curl',
        name: 'כפיפת ברך בישיבה',
        name_en: 'Seated Leg Curl',
        videoId: 'ELOCsoDSmrg',
        sets: 3,
        reps: '12-15',
        rest: 120,
        tempo: '1:1:3',
        superset: 'C',
        notes_he: 'להצמיד ישבן לגב הספסל, לשמור על כף רגל כלפי מעלה ולאחוז בידיים.',
        notes: 'Glue your glutes to the back of the seat, keep feet pointing up, hold with hands.',
      },
      // Calves
      {
        key: 'smith_calf_raise',
        name: 'עליות תאומים בסמית׳',
        name_en: 'Smith Machine Calf Raises',
        videoId: 'FNdI5TynYxs',
        sets: 3,
        reps: '21 (7×3)',
        rest: 60,
        superset: null,
        notes_he: '3 זוויות - לבצע 7 חזרות עם כפות רגליים כלפי חוץ, 7 ישר, 7 כלפי פנים.',
        notes: '3 foot positions - perform 7 reps with toes pointed out, 7 reps straight, 7 reps toes pointed in.',
      },
      // Abs
      {
        key: 'bosu_weighted_crunches',
        name: 'כפיפות בטן על בוסו עם משקל',
        name_en: 'Bosu Ball Weighted Crunches',
        videoId: 'HNZjpnyu3Q8',
        sets: 3,
        reps: '12-15',
        rest: 60,
        superset: null,
      },
      {
        key: 'decline_crunches',
        name: 'כפיפות בטן בשיפוע תחתון',
        name_en: 'Decline Crunches',
        videoId: 'uaSOakFICBY',
        sets: 3,
        reps: '12-15',
        rest: 60,
        superset: null,
        notes_he: 'לצפות בסרטון - דגשים חשובים!',
        notes: 'Watch the video for important technique cues!',
      },
    ],
  },
  {
    id: 'abc_full',
    name: 'Full Body',
    name_he: 'גוף מלא',
    color: '#F97316',
    muscles: ['Back', 'Chest', 'Shoulders', 'Arms', 'Legs', 'Abs'],
    sort_order: 6,
    program: 'abc_recomp',
    exercises: [
      // Back
      {
        key: 'wide_grip_lat_pulldown',
        name: 'משיכה בפולי אחיזה רחבה',
        name_en: 'Wide Grip Lat Pulldown',
        videoId: '7JnP8dFbS14',
        sets: 3,
        reps: '8-10',
        rest: 120,
        superset: null,
        notes_he: 'לשבת הכי צמוד לכיסא, ישבן עד הסוף לפנים, להשען אחורה 10 מעלות.',
        notes: 'Sit as close to the pad as possible, glutes all the way forward, lean back approximately 10 degrees.',
      },
      {
        key: 'wide_grip_cable_row',
        name: 'חתירה אחיזה רחבה בפולי',
        name_en: 'Wide Grip Cable Row',
        videoId: 'y7h823PdWIY',
        sets: 3,
        reps: '8-10',
        rest: 120,
        superset: null,
        notes_he: 'לכווץ את השכמות במשיכה ולשחרר אותם בסוף כל חזרה, להביא את המוט אל הגוף.',
        notes: 'Squeeze scapulae on the pull and release them at the end of each rep.',
      },
      // Chest/Rear Delts superset C
      {
        key: 'incline_db_press',
        name: 'לחיצת חזה עליון עם משקולות',
        name_en: 'Dumbbell Incline Press',
        videoId: 'hChjZQhX1Ls',
        sets: 3,
        reps: '6-8',
        superset: 'C',
        notes_he: 'רגליים נעוצות על הקרקע בשביל יציבות טובה וליצור זווית של 90 מעלות.',
        notes: 'Feet planted firmly on the ground for stability, create a 90-degree angle at the elbow.',
      },
      {
        key: 'seated_reverse_fly',
        name: 'הרחקה אופקית בישיבה',
        name_en: 'Seated Reverse Fly',
        videoId: '8iB5-YKcS3g',
        sets: 3,
        reps: '12-15',
        rest: 60,
        superset: 'C',
        notes_he: 'לשכב על ספסל בזווית 30 מעלות להוציא את החזה קצת החוצה.',
        notes: 'Lie on a bench at 30 degrees, push chest slightly outward.',
      },
      // Shoulders
      {
        key: 'db_lateral_raise',
        name: 'הרחקות כתפיים כנגד משקולות',
        name_en: 'DB Lateral Raises',
        videoId: 'XPPfnSEATJA',
        sets: 3,
        reps: '8-12',
        rest: 60,
        superset: null,
        notes_he: 'להרים עד גובה כתפיים, לשמור על יד ישרה ולהשען קצת קדימה.',
        notes: 'Raise to shoulder height, keep arms straight, lean slightly forward.',
      },
      // Arms superset E
      {
        key: 'cable_bar_pushdown',
        name: 'פשיטת מרפק בקרוס עם מוט',
        name_en: 'Cable Bar Tricep Pushdown',
        videoId: '2-LAMcpzODU',
        sets: 3,
        reps: '8-10',
        superset: 'E',
        notes_he: 'לשים דגש עם טווח תנועה מלא ותנועה איטית, מרפקים צמודים לגוף.',
        notes: 'Emphasize full range of motion and slow movement, keep elbows tight to body.',
      },
      {
        key: 'cable_bar_curl',
        name: 'כפיפת מרפק בקרוס עם מוט',
        name_en: 'Cable Bar Curl',
        videoId: 'k_oxpDonR8s',
        sets: 3,
        reps: '8-12',
        rest: 60,
        tempo: '1:2:3',
        superset: 'E',
        notes_he: 'להניח את המרפקים על הצלעות ולהוריד את הכתפיים (והשכמות) למטה.',
        notes: 'Place elbows against ribs, pull shoulders and scapulae down.',
      },
      // Legs superset F
      {
        key: 'sissy_squat',
        name: 'סיסי סקוואט',
        name_en: 'Sissy Squat',
        videoId: 'VUiFlZ2FsKA',
        sets: 3,
        reps: '8-10',
        superset: 'F',
        notes_he: 'לשמור על ישבן מכווץ חזק לאורך כל התנועה, להיעזר עם יד אחת לשיווי משקל.',
        notes: 'Keep glutes squeezed tight throughout, assist with one hand for balance.',
      },
      {
        key: 'seated_leg_curl',
        name: 'כפיפת ברך בישיבה',
        name_en: 'Seated Leg Curl',
        videoId: 'ELOCsoDSmrg',
        sets: 3,
        reps: '8-12',
        rest: 120,
        tempo: '1:1:3',
        superset: 'F',
        notes_he: 'להצמיד ישבן לגב הספסל, לשמור על כף רגל כלפי מעלה ולאחוז בידיים.',
        notes: 'Glue glutes to seat back, keep feet pointing up, hold with hands.',
      },
      // Calves
      {
        key: 'smith_calf_raise',
        name: 'עליות תאומים בסמית׳',
        name_en: 'Smith Machine Calf Raises',
        videoId: 'FNdI5TynYxs',
        sets: 3,
        reps: '8-12',
        rest: 60,
        superset: null,
        notes_he: 'לבצע 3 זוויות - סט ראשון כפות רגליים פונות החוצה, סט שני ישר, סט שלישי פנימה.',
        notes: '3 foot angles - toes out / straight / toes in.',
      },
      // Abs
      {
        key: 'bosu_weighted_crunches',
        name: 'כפיפות בטן על בוסו עם משקל',
        name_en: 'Bosu Ball Weighted Crunches',
        videoId: 'HNZjpnyu3Q8',
        sets: 3,
        reps: '12-15',
        rest: 60,
        superset: null,
      },
    ],
  },
]
