export const MEAL_PLANS = [
  {
    id: 'bulk-default',
    name: 'Bulk',
    active: true,
    start_date: '2026-04-24',
    end_date: '2026-05-19',
    meals: [
      {
        id: 'breakfast-1',
        name: 'Breakfast 1',
        sort_order: 1,
        target_kcal: 104,
        target_protein: 0,
        target_carbs: 26,
        target_fat: 0,
        foods: [
          { name: 'Medjool Date', qty: 2, unit: 'Qty', kcal: 104, protein: 0, carbs: 26, fat: 0 },
        ],
      },
      {
        id: 'breakfast-2',
        name: 'Breakfast 2',
        sort_order: 2,
        target_kcal: 391,
        target_protein: 28,
        target_carbs: 28,
        target_fat: 10,
        foods: [
          { name: 'Cottage Cheese 3% / Tuna in Oil / 2 Eggs', qty: 1, unit: 'Qty', kcal: 193, protein: 28, carbs: 3.8, fat: 7.5 },
          { name: 'Light Pita / 1.5 Bread Slices', qty: 2, unit: 'Qty', kcal: 198, protein: 0, carbs: 24, fat: 2.1 },
        ],
      },
      {
        id: 'snack-1',
        name: 'Snack 1',
        sort_order: 3,
        target_kcal: 436,
        target_protein: 28,
        target_carbs: 28,
        target_fat: 15,
        foods: [
          { name: 'Cottage Cheese 5%', qty: 1, unit: 'Qty', kcal: 238, protein: 28, carbs: 3.8, fat: 13 },
          { name: 'Light Pita / 1.5 Bread Slices', qty: 2, unit: 'Qty', kcal: 198, protein: 0, carbs: 24, fat: 2.1 },
        ],
      },
      {
        id: 'lunch',
        name: 'Lunch',
        sort_order: 4,
        target_kcal: 1000,
        target_protein: 66,
        target_carbs: 101,
        target_fat: 20,
        foods: [
          { name: 'Chicken Breast / Thigh', qty: 200, unit: 'g', kcal: 328, protein: 66, carbs: 0, fat: 7.1 },
          { name: 'Rice 350g / Potato 550g', qty: 350, unit: 'g', kcal: 455, protein: 0, carbs: 95, fat: 0.7 },
          { name: 'Raw Tahini', qty: 20, unit: 'g', kcal: 137, protein: 0, carbs: 2.4, fat: 12 },
          { name: 'Roasted Vegetables', qty: 200, unit: 'g', kcal: 80, protein: 0, carbs: 4, fat: 0.5 },
        ],
      },
      {
        id: 'snack-2',
        name: 'Snack 2',
        sort_order: 5,
        target_kcal: 470,
        target_protein: 11,
        target_carbs: 76,
        target_fat: 7,
        foods: [
          { name: 'Cottage Cheese 5%', qty: 100, unit: 'g', kcal: 95, protein: 11, carbs: 1.5, fat: 5 },
          { name: '5 Bread Slices / 1.5 Pita / 1.5 Bun', qty: 1.5, unit: 'Qty', kcal: 375, protein: 0, carbs: 74, fat: 2.1 },
        ],
      },
      {
        id: 'dinner',
        name: 'Dinner',
        sort_order: 6,
        target_kcal: 666,
        target_protein: 33,
        target_carbs: 70,
        target_fat: 16,
        foods: [
          { name: 'Chicken Breast / Thigh', qty: 100, unit: 'g', kcal: 164, protein: 33, carbs: 0, fat: 3.6 },
          { name: 'Rice', qty: 250, unit: 'g', kcal: 325, protein: 0, carbs: 68, fat: 0.5 },
          { name: 'Raw Tahini', qty: 20, unit: 'g', kcal: 137, protein: 0, carbs: 2.4, fat: 12 },
          { name: 'Mixed Vegetables (2-3)', qty: 1, unit: 'Qty', kcal: 40, protein: 0, carbs: 0, fat: 0 },
        ],
      },
      {
        id: 'free-calories',
        name: 'Free Calories',
        sort_order: 7,
        target_kcal: 200,
        target_protein: 0,
        target_carbs: 0,
        target_fat: 0,
        foods: [
          { name: 'Free Calories', qty: 1, unit: 'Qty', kcal: 200, protein: 0, carbs: 0, fat: 0 },
        ],
      },
    ],
  },
  {
    id: 'mini-cut',
    name: 'Mini Cut',
    active: false,
    start_date: '2026-04-12',
    end_date: '2026-04-23',
    meals: [
      {
        id: 'breakfast-1',
        name: 'Breakfast 1',
        sort_order: 1,
        target_kcal: 104,
        target_protein: 0,
        target_carbs: 26,
        target_fat: 0,
        foods: [
          { name: 'Medjool Date', qty: 2, unit: 'Qty', kcal: 104, protein: 0, carbs: 26, fat: 0 },
        ],
      },
      {
        id: 'breakfast-2',
        name: 'Breakfast 2',
        sort_order: 2,
        target_kcal: 391,
        target_protein: 28,
        target_carbs: 28,
        target_fat: 10,
        foods: [
          { name: 'Cottage Cheese 3% / Tuna in Oil / 2 Eggs', qty: 1, unit: 'Qty', kcal: 193, protein: 28, carbs: 3.8, fat: 7.5 },
          { name: 'Light Pita / 1.5 Bread Slices', qty: 2, unit: 'Qty', kcal: 198, protein: 0, carbs: 24, fat: 2.1 },
        ],
      },
      {
        id: 'snack-1',
        name: 'Snack 1',
        sort_order: 3,
        target_kcal: 436,
        target_protein: 28,
        target_carbs: 28,
        target_fat: 15,
        foods: [
          { name: 'Cottage Cheese 5%', qty: 1, unit: 'Qty', kcal: 238, protein: 28, carbs: 3.8, fat: 13 },
          { name: 'Light Pita / 1.5 Bread Slices', qty: 2, unit: 'Qty', kcal: 198, protein: 0, carbs: 24, fat: 2.1 },
        ],
      },
      {
        id: 'lunch',
        name: 'Lunch',
        sort_order: 4,
        target_kcal: 870,
        target_protein: 66,
        target_carbs: 74,
        target_fat: 20,
        foods: [
          { name: 'Chicken Breast / Thigh', qty: 200, unit: 'g', kcal: 328, protein: 66, carbs: 0, fat: 7.1 },
          { name: 'Rice 250g / Potato 400g', qty: 250, unit: 'g', kcal: 325, protein: 0, carbs: 68, fat: 0.5 },
          { name: 'Raw Tahini', qty: 20, unit: 'g', kcal: 137, protein: 0, carbs: 2.4, fat: 12 },
          { name: 'Roasted Vegetables', qty: 200, unit: 'g', kcal: 80, protein: 0, carbs: 4, fat: 0.5 },
        ],
      },
      {
        id: 'dinner',
        name: 'Dinner',
        sort_order: 5,
        target_kcal: 666,
        target_protein: 33,
        target_carbs: 70,
        target_fat: 16,
        foods: [
          { name: 'Chicken Breast / Thigh', qty: 100, unit: 'g', kcal: 164, protein: 33, carbs: 0, fat: 3.6 },
          { name: 'Rice', qty: 250, unit: 'g', kcal: 325, protein: 0, carbs: 68, fat: 0.5 },
          { name: 'Raw Tahini', qty: 20, unit: 'g', kcal: 137, protein: 0, carbs: 2.4, fat: 12 },
          { name: 'Mixed Vegetables (2-3)', qty: 1, unit: 'Qty', kcal: 40, protein: 0, carbs: 0, fat: 0 },
        ],
      },
      {
        id: 'free-calories',
        name: 'Free Calories',
        sort_order: 6,
        target_kcal: 100,
        target_protein: 0,
        target_carbs: 0,
        target_fat: 0,
        foods: [
          { name: 'Free Calories', qty: 1, unit: 'Qty', kcal: 100, protein: 0, carbs: 0, fat: 0 },
        ],
      },
    ],
  },
  {
    id: 'cut',
    name: 'Cut',
    active: false,
    start_date: '2026-05-20',
    end_date: '2026-07-14',
    meals: [
      {
        id: 'breakfast-1',
        name: 'Breakfast 1',
        sort_order: 1,
        target_kcal: 104,
        target_protein: 0,
        target_carbs: 26,
        target_fat: 0,
        foods: [
          { name: 'Medjool Date', qty: 2, unit: 'Qty', kcal: 104, protein: 0, carbs: 26, fat: 0 },
        ],
      },
      {
        id: 'breakfast-2',
        name: 'Breakfast 2',
        sort_order: 2,
        target_kcal: 391,
        target_protein: 28,
        target_carbs: 28,
        target_fat: 10,
        foods: [
          { name: 'Cottage Cheese 3% / Tuna in Oil / 2 Eggs', qty: 1, unit: 'Qty', kcal: 193, protein: 28, carbs: 3.8, fat: 7.5 },
          { name: 'Light Pita / 1.5 Bread Slices', qty: 2, unit: 'Qty', kcal: 198, protein: 0, carbs: 24, fat: 2.1 },
        ],
      },
      {
        id: 'snack-1',
        name: 'Snack 1',
        sort_order: 3,
        target_kcal: 436,
        target_protein: 28,
        target_carbs: 28,
        target_fat: 15,
        foods: [
          { name: 'Cottage Cheese 5%', qty: 1, unit: 'Qty', kcal: 238, protein: 28, carbs: 3.8, fat: 13 },
          { name: 'Light Pita / 1.5 Bread Slices', qty: 2, unit: 'Qty', kcal: 198, protein: 0, carbs: 24, fat: 2.1 },
        ],
      },
      {
        id: 'lunch',
        name: 'Lunch',
        sort_order: 4,
        target_kcal: 1000,
        target_protein: 66,
        target_carbs: 101,
        target_fat: 20,
        foods: [
          { name: 'Chicken Breast / Thigh', qty: 200, unit: 'g', kcal: 328, protein: 66, carbs: 0, fat: 7.1 },
          { name: 'Rice 350g / Potato 550g', qty: 350, unit: 'g', kcal: 455, protein: 0, carbs: 95, fat: 0.7 },
          { name: 'Raw Tahini', qty: 20, unit: 'g', kcal: 137, protein: 0, carbs: 2.4, fat: 12 },
          { name: 'Roasted Vegetables', qty: 200, unit: 'g', kcal: 80, protein: 0, carbs: 4, fat: 0.5 },
        ],
      },
      {
        id: 'dinner',
        name: 'Dinner',
        sort_order: 5,
        target_kcal: 666,
        target_protein: 33,
        target_carbs: 70,
        target_fat: 16,
        foods: [
          { name: 'Chicken Breast / Thigh', qty: 100, unit: 'g', kcal: 164, protein: 33, carbs: 0, fat: 3.6 },
          { name: 'Rice', qty: 250, unit: 'g', kcal: 325, protein: 0, carbs: 68, fat: 0.5 },
          { name: 'Raw Tahini', qty: 20, unit: 'g', kcal: 137, protein: 0, carbs: 2.4, fat: 12 },
          { name: 'Mixed Vegetables (2-3)', qty: 1, unit: 'Qty', kcal: 40, protein: 0, carbs: 0, fat: 0 },
        ],
      },
      {
        id: 'free-calories',
        name: 'Free Calories',
        sort_order: 6,
        target_kcal: 200,
        target_protein: 0,
        target_carbs: 0,
        target_fat: 0,
        foods: [
          { name: 'Free Calories', qty: 1, unit: 'Qty', kcal: 200, protein: 0, carbs: 0, fat: 0 },
        ],
      },
    ],
  },
]
