export const MEAL_PLANS = [
  {
    id: 'mini-cut',
    name: 'Mini Cut',
    active: false,
    start_date: '2026-04-13',
    end_date: '2026-04-28',
    meals: [
      {
        id: 'breakfast-1',
        name: 'Breakfast 1',
        sort_order: 1,
        target_kcal: 104,
        target_protein: 0,
        target_carbs: 26,
        target_fat: 0,
        foods: [
          { name: 'Medjool Date', qty: 2, unit: 'Qty', kcal: 104, protein: 0, carbs: 26, fat: 0 },
        ],
      },
      {
        id: 'breakfast-2',
        name: 'Breakfast 2',
        sort_order: 2,
        target_kcal: 391,
        target_protein: 28,
        target_carbs: 28,
        target_fat: 10,
        foods: [
          { name: 'Cottage Cheese 3% / Tuna in Oil / 2 Eggs', qty: 1, unit: 'Qty', kcal: 193, protein: 28, carbs: 3.8, fat: 7.5 },
          { name: 'Light Pita / 1.5 Bread Slices', qty: 2, unit: 'Qty', kcal: 198, protein: 0, carbs: 24, fat: 2.1 },
        ],
      },
      {
        id: 'snack-1',
        name: 'Snack 1',
        sort_order: 3,
        target_kcal: 436,
        target_protein: 28,
        target_carbs: 28,
        target_fat: 15,
        foods: [
          { name: 'Cottage Cheese 5%', qty: 1, unit: 'Qty', kcal: 238, protein: 28, carbs: 3.8, fat: 13 },
          { name: 'Light Pita / 1.5 Bread Slices', qty: 2, unit: 'Qty', kcal: 198, protein: 0, carbs: 24, fat: 2.1 },
        ],
      },
      {
        id: 'lunch',
        name: 'Lunch',
        sort_order: 4,
        target_kcal: 870,
        target_protein: 66,
        target_carbs: 74,
        target_fat: 20,
        foods: [
          { name: 'Chicken Breast / Thigh', qty: 200, unit: 'g', kcal: 328, protein: 66, carbs: 0, fat: 7.1 },
          { name: 'Rice 250g / Potato 400g', qty: 250, unit: 'g', kcal: 325, protein: 0, carbs: 68, fat: 0.5 },
          { name: 'Raw Tahini', qty: 20, unit: 'g', kcal: 137, protein: 0, carbs: 2.4, fat: 12 },
          { name: 'Roasted Vegetables', qty: 200, unit: 'g', kcal: 80, protein: 0, carbs: 4, fat: 0.5 },
        ],
      },
      {
        id: 'dinner',
        name: 'Dinner',
        sort_order: 5,
        target_kcal: 666,
        target_protein: 33,
        target_carbs: 70,
        target_fat: 16,
        foods: [
          { name: 'Chicken Breast / Thigh', qty: 100, unit: 'g', kcal: 164, protein: 33, carbs: 0, fat: 3.6 },
          { name: 'Rice', qty: 250, unit: 'g', kcal: 325, protein: 0, carbs: 68, fat: 0.5 },
          { name: 'Raw Tahini', qty: 20, unit: 'g', kcal: 137, protein: 0, carbs: 2.4, fat: 12 },
          { name: 'Mixed Vegetables (2-3)', qty: 1, unit: 'Qty', kcal: 40, protein: 0, carbs: 0, fat: 0 },
        ],
      },
      {
        id: 'free-calories',
        name: 'Free Calories',
        sort_order: 6,
        target_kcal: 100,
        target_protein: 0,
        target_carbs: 0,
        target_fat: 0,
        foods: [
          { name: 'Free Calories', qty: 1, unit: 'Qty', kcal: 100, protein: 0, carbs: 0, fat: 0 },
        ],
      },
    ],
  },
  {
    id: 'cut',
    name: 'Cut',
    active: true,
    start_date: '2026-04-29',
    end_date: '2026-05-31',
    meals: [
      {
        id: 'pre-workout',
        name: 'Pre-Workout',
        sort_order: 1,
        target_kcal: 104,
        target_protein: 0,
        target_carbs: 26,
        target_fat: 0,
        foods: [
          { name: 'Medjool Date', qty: 2, unit: 'Qty', kcal: 104, protein: 0, carbs: 26, fat: 0 },
        ],
        alternatives: [
          {
            id: 'preworkout-banana',
            name: 'Banana',
            target_kcal: 105,
            target_protein: 1,
            target_carbs: 27,
            target_fat: 0.4,
            foods: [
              { name: 'Medium Banana', qty: 1, unit: 'Qty', kcal: 105, protein: 1, carbs: 27, fat: 0.4 },
            ],
          },
          {
            id: 'preworkout-ricecake',
            name: 'Rice Cake + Honey (V)',
            target_kcal: 100,
            target_protein: 1,
            target_carbs: 23,
            target_fat: 0.5,
            foods: [
              { name: 'Rice Cakes', qty: 2, unit: 'Qty', kcal: 70, protein: 1, carbs: 16, fat: 0.3 },
              { name: 'Honey', qty: 1, unit: 'tsp', kcal: 30, protein: 0, carbs: 7, fat: 0.2 },
            ],
          },
          {
            id: 'preworkout-apple',
            name: 'Apple',
            target_kcal: 95,
            target_protein: 0.5,
            target_carbs: 25,
            target_fat: 0.3,
            foods: [
              { name: 'Medium Apple', qty: 1, unit: 'Qty', kcal: 95, protein: 0.5, carbs: 25, fat: 0.3 },
            ],
          },
          {
            id: 'preworkout-apricots',
            name: 'Dried Apricots (V)',
            target_kcal: 84,
            target_protein: 1,
            target_carbs: 22,
            target_fat: 0.2,
            foods: [
              { name: 'Dried Apricots', qty: 5, unit: 'Qty', kcal: 84, protein: 1, carbs: 22, fat: 0.2 },
            ],
          },
        ],
      },
      {
        id: 'breakfast',
        name: 'Breakfast',
        sort_order: 2,
        target_kcal: 760,
        target_protein: 44,
        target_carbs: 88,
        target_fat: 25,
        foods: [
          { name: 'Eggs (L)', qty: 4, unit: 'Qty', kcal: 290, protein: 25, carbs: 1.5, fat: 20 },
          { name: 'Organic Tomato Paste', qty: 200, unit: 'g', kcal: 70, protein: 3, carbs: 14, fat: 0.6 },
          { name: 'Spelt Bread', qty: 4, unit: 'Slices', kcal: 400, protein: 16, carbs: 72, fat: 4 },
        ],
        alternatives: [
          {
            id: 'breakfast-tofu-shakshuka',
            name: 'Tofu Shakshuka (V)',
            target_kcal: 695,
            target_protein: 45,
            target_carbs: 91,
            target_fat: 18,
            foods: [
              { name: 'Firm Tofu', qty: 150, unit: 'g', kcal: 225, protein: 25.5, carbs: 4.5, fat: 13.5 },
              { name: 'Organic Tomato Paste', qty: 200, unit: 'g', kcal: 70, protein: 3, carbs: 14, fat: 0.6 },
              { name: 'Spelt Bread', qty: 4, unit: 'Slices', kcal: 400, protein: 16, carbs: 72, fat: 4 },
            ],
          },
          {
            id: 'breakfast-oatmeal',
            name: 'Power Oatmeal (V)',
            target_kcal: 795,
            target_protein: 47,
            target_carbs: 105,
            target_fat: 23,
            foods: [
              { name: 'Oats (dry)', qty: 100, unit: 'g', kcal: 389, protein: 13, carbs: 67, fat: 7 },
              { name: 'Peanut Butter', qty: 30, unit: 'g', kcal: 176, protein: 7, carbs: 6, fat: 15 },
              { name: 'Banana', qty: 1, unit: 'Qty', kcal: 105, protein: 1, carbs: 27, fat: 0.4 },
              { name: 'Protein Powder', qty: 30, unit: 'g', kcal: 125, protein: 26, carbs: 5, fat: 0.6 },
            ],
          },
          {
            id: 'breakfast-avocado',
            name: 'Avocado Egg Toast',
            target_kcal: 697,
            target_protein: 38,
            target_carbs: 61,
            target_fat: 32,
            foods: [
              { name: 'Eggs (L)', qty: 4, unit: 'Qty', kcal: 288, protein: 25, carbs: 1.5, fat: 19.2 },
              { name: 'Avocado', qty: 0.5, unit: 'Qty', kcal: 109, protein: 1, carbs: 6, fat: 10 },
              { name: 'Spelt Bread', qty: 3, unit: 'Slices', kcal: 300, protein: 12, carbs: 54, fat: 3 },
            ],
          },
          {
            id: 'breakfast-chickpea',
            name: 'Chickpea Shakshuka (V)',
            target_kcal: 780,
            target_protein: 37,
            target_carbs: 137,
            target_fat: 10,
            foods: [
              { name: 'Cooked Chickpeas', qty: 250, unit: 'g', kcal: 410, protein: 22, carbs: 69, fat: 6.5 },
              { name: 'Organic Tomato Paste', qty: 200, unit: 'g', kcal: 70, protein: 3, carbs: 14, fat: 0.6 },
              { name: 'Spelt Bread', qty: 3, unit: 'Slices', kcal: 300, protein: 12, carbs: 54, fat: 3 },
            ],
          },
        ],
      },
      {
        id: 'lunch',
        name: 'Lunch',
        sort_order: 3,
        target_kcal: 994,
        target_protein: 77,
        target_carbs: 120,
        target_fat: 19,
        foods: [
          { name: 'Chicken Breast / Thigh', qty: 200, unit: 'g', kcal: 330, protein: 62, carbs: 0, fat: 7.1 },
          { name: 'Rice 350g / Potato 550g', qty: 350, unit: 'g', kcal: 455, protein: 9, carbs: 98, fat: 1 },
          { name: 'Raw Tahini', qty: 20, unit: 'g', kcal: 119, protein: 3.4, carbs: 4.2, fat: 10.8 },
          { name: 'Roasted Vegetables', qty: 200, unit: 'g', kcal: 90, protein: 3, carbs: 18, fat: 0.5 },
        ],
        alternatives: [
          {
            id: 'lunch-salmon',
            name: 'Salmon',
            target_kcal: 887,
            target_protein: 60,
            target_carbs: 116,
            target_fat: 17.5,
            foods: [
              { name: 'Salmon Fillet', qty: 200, unit: 'g', kcal: 342, protein: 48, carbs: 0, fat: 16 },
              { name: 'Rice 350g / Potato 550g', qty: 350, unit: 'g', kcal: 455, protein: 9, carbs: 98, fat: 1 },
              { name: 'Roasted Vegetables', qty: 200, unit: 'g', kcal: 90, protein: 3, carbs: 18, fat: 0.5 },
            ],
          },
          {
            id: 'lunch-tofu',
            name: 'Tofu (V)',
            target_kcal: 920,
            target_protein: 55,
            target_carbs: 124,
            target_fat: 24,
            foods: [
              { name: 'Firm Tofu', qty: 250, unit: 'g', kcal: 375, protein: 42.5, carbs: 7.5, fat: 22.5 },
              { name: 'Rice 350g / Potato 550g', qty: 350, unit: 'g', kcal: 455, protein: 9, carbs: 98, fat: 1 },
              { name: 'Roasted Vegetables', qty: 200, unit: 'g', kcal: 90, protein: 3, carbs: 18, fat: 0.5 },
            ],
          },
          {
            id: 'lunch-beef',
            name: 'Lean Beef',
            target_kcal: 925,
            target_protein: 68,
            target_carbs: 116,
            target_fat: 18,
            foods: [
              { name: 'Lean Beef (Sirloin)', qty: 200, unit: 'g', kcal: 380, protein: 56, carbs: 0, fat: 16 },
              { name: 'Rice 350g / Potato 550g', qty: 350, unit: 'g', kcal: 455, protein: 9, carbs: 98, fat: 1 },
              { name: 'Roasted Vegetables', qty: 200, unit: 'g', kcal: 90, protein: 3, carbs: 18, fat: 0.5 },
            ],
          },
          {
            id: 'lunch-lentils',
            name: 'Lentil Bowl (V)',
            target_kcal: 889,
            target_protein: 37,
            target_carbs: 157,
            target_fat: 13,
            foods: [
              { name: 'Cooked Lentils', qty: 250, unit: 'g', kcal: 290, protein: 22, carbs: 50, fat: 1 },
              { name: 'Rice', qty: 300, unit: 'g', kcal: 390, protein: 8, carbs: 85, fat: 0.8 },
              { name: 'Raw Tahini', qty: 20, unit: 'g', kcal: 119, protein: 3.4, carbs: 4.2, fat: 10.8 },
              { name: 'Roasted Vegetables', qty: 200, unit: 'g', kcal: 90, protein: 3, carbs: 18, fat: 0.5 },
            ],
          },
        ],
      },
      {
        id: 'dinner',
        name: 'Dinner',
        sort_order: 4,
        target_kcal: 649,
        target_protein: 41,
        target_carbs: 74,
        target_fat: 15,
        foods: [
          { name: 'Chicken Breast / Thigh', qty: 100, unit: 'g', kcal: 165, protein: 31, carbs: 0, fat: 3.6 },
          { name: 'Rice', qty: 250, unit: 'g', kcal: 325, protein: 6.7, carbs: 70, fat: 0.7 },
          { name: 'Raw Tahini', qty: 20, unit: 'g', kcal: 119, protein: 3.4, carbs: 4.2, fat: 10.8 },
          { name: 'Mixed Vegetables (2-3)', qty: 1, unit: 'Qty', kcal: 40, protein: 0, carbs: 0, fat: 0 },
        ],
        alternatives: [
          {
            id: 'dinner-fish',
            name: 'Fish + Sweet Potato',
            target_kcal: 666,
            target_protein: 49,
            target_carbs: 78,
            target_fat: 15,
            foods: [
              { name: 'White Fish (Tilapia/Sea Bream)', qty: 150, unit: 'g', kcal: 192, protein: 39, carbs: 0, fat: 3.9 },
              { name: 'Sweet Potato', qty: 350, unit: 'g', kcal: 315, protein: 7, carbs: 73.5, fat: 0.35 },
              { name: 'Raw Tahini', qty: 20, unit: 'g', kcal: 119, protein: 3.4, carbs: 4.2, fat: 10.8 },
              { name: 'Mixed Vegetables (2-3)', qty: 1, unit: 'Qty', kcal: 40, protein: 0, carbs: 0, fat: 0 },
            ],
          },
          {
            id: 'dinner-tofu',
            name: 'Tofu (V)',
            target_kcal: 665,
            target_protein: 41,
            target_carbs: 76,
            target_fat: 19,
            foods: [
              { name: 'Firm Tofu', qty: 200, unit: 'g', kcal: 300, protein: 34, carbs: 6, fat: 18 },
              { name: 'Rice', qty: 250, unit: 'g', kcal: 325, protein: 6.7, carbs: 70, fat: 0.7 },
              { name: 'Mixed Vegetables (2-3)', qty: 1, unit: 'Qty', kcal: 40, protein: 0, carbs: 0, fat: 0 },
            ],
          },
          {
            id: 'dinner-salmon-sp',
            name: 'Salmon + Sweet Potato',
            target_kcal: 657,
            target_protein: 44,
            target_carbs: 83,
            target_fat: 13,
            foods: [
              { name: 'Salmon Fillet', qty: 150, unit: 'g', kcal: 257, protein: 36, carbs: 0, fat: 12 },
              { name: 'Sweet Potato', qty: 400, unit: 'g', kcal: 360, protein: 8, carbs: 83, fat: 0.6 },
              { name: 'Mixed Vegetables (2-3)', qty: 1, unit: 'Qty', kcal: 40, protein: 0, carbs: 0, fat: 0 },
            ],
          },
          {
            id: 'dinner-lentils',
            name: 'Lentil Stew (V)',
            target_kcal: 651,
            target_protein: 27,
            target_carbs: 100,
            target_fat: 12,
            foods: [
              { name: 'Cooked Lentils', qty: 200, unit: 'g', kcal: 232, protein: 18, carbs: 40, fat: 0.8 },
              { name: 'Rice', qty: 200, unit: 'g', kcal: 260, protein: 5.4, carbs: 56, fat: 0.6 },
              { name: 'Raw Tahini', qty: 20, unit: 'g', kcal: 119, protein: 3.4, carbs: 4.2, fat: 10.8 },
              { name: 'Mixed Vegetables (2-3)', qty: 1, unit: 'Qty', kcal: 40, protein: 0, carbs: 0, fat: 0 },
            ],
          },
        ],
      },
      {
        id: 'free-calories',
        name: 'Free Calories',
        sort_order: 5,
        target_kcal: 200,
        target_protein: 0,
        target_carbs: 0,
        target_fat: 0,
        foods: [
          { name: 'Free Calories', qty: 1, unit: 'Qty', kcal: 200, protein: 0, carbs: 0, fat: 0 },
        ],
      },
    ],
  },
  {
    id: 'bulk-june',
    name: 'Bulk',
    active: false,
    start_date: '2026-06-01',
    end_date: '2026-07-27',
    meals: [
      {
        id: 'breakfast-1',
        name: 'Breakfast 1',
        sort_order: 1,
        target_kcal: 104,
        target_protein: 0,
        target_carbs: 26,
        target_fat: 0,
        foods: [
          { name: 'Medjool Date', qty: 2, unit: 'Qty', kcal: 104, protein: 0, carbs: 26, fat: 0 },
        ],
      },
      {
        id: 'breakfast-2',
        name: 'Breakfast 2',
        sort_order: 2,
        target_kcal: 391,
        target_protein: 28,
        target_carbs: 28,
        target_fat: 10,
        foods: [
          { name: 'Cottage Cheese 3% / Tuna in Oil / 2 Eggs', qty: 1, unit: 'Qty', kcal: 193, protein: 28, carbs: 3.8, fat: 7.5 },
          { name: 'Light Pita / 1.5 Bread Slices', qty: 2, unit: 'Qty', kcal: 198, protein: 0, carbs: 24, fat: 2.1 },
        ],
      },
      {
        id: 'snack-1',
        name: 'Snack 1',
        sort_order: 3,
        target_kcal: 436,
        target_protein: 28,
        target_carbs: 28,
        target_fat: 15,
        foods: [
          { name: 'Cottage Cheese 5%', qty: 1, unit: 'Qty', kcal: 238, protein: 28, carbs: 3.8, fat: 13 },
          { name: 'Light Pita / 1.5 Bread Slices', qty: 2, unit: 'Qty', kcal: 198, protein: 0, carbs: 24, fat: 2.1 },
        ],
      },
      {
        id: 'lunch',
        name: 'Lunch',
        sort_order: 4,
        target_kcal: 1000,
        target_protein: 66,
        target_carbs: 101,
        target_fat: 20,
        foods: [
          { name: 'Chicken Breast / Thigh', qty: 200, unit: 'g', kcal: 328, protein: 66, carbs: 0, fat: 7.1 },
          { name: 'Rice 350g / Potato 550g', qty: 350, unit: 'g', kcal: 455, protein: 0, carbs: 95, fat: 0.7 },
          { name: 'Raw Tahini', qty: 20, unit: 'g', kcal: 137, protein: 0, carbs: 2.4, fat: 12 },
          { name: 'Roasted Vegetables', qty: 200, unit: 'g', kcal: 80, protein: 0, carbs: 4, fat: 0.5 },
        ],
      },
      {
        id: 'snack-2',
        name: 'Snack 2',
        sort_order: 5,
        target_kcal: 470,
        target_protein: 11,
        target_carbs: 76,
        target_fat: 7,
        foods: [
          { name: 'Cottage Cheese 5%', qty: 100, unit: 'g', kcal: 95, protein: 11, carbs: 1.5, fat: 5 },
          { name: '5 Bread Slices / 1.5 Pita / 1.5 Bun', qty: 1.5, unit: 'Qty', kcal: 375, protein: 0, carbs: 74, fat: 2.1 },
        ],
      },
      {
        id: 'dinner',
        name: 'Dinner',
        sort_order: 6,
        target_kcal: 666,
        target_protein: 33,
        target_carbs: 70,
        target_fat: 16,
        foods: [
          { name: 'Chicken Breast / Thigh', qty: 100, unit: 'g', kcal: 164, protein: 33, carbs: 0, fat: 3.6 },
          { name: 'Rice', qty: 250, unit: 'g', kcal: 325, protein: 0, carbs: 68, fat: 0.5 },
          { name: 'Raw Tahini', qty: 20, unit: 'g', kcal: 137, protein: 0, carbs: 2.4, fat: 12 },
          { name: 'Mixed Vegetables (2-3)', qty: 1, unit: 'Qty', kcal: 40, protein: 0, carbs: 0, fat: 0 },
        ],
      },
      {
        id: 'free-calories',
        name: 'Free Calories',
        sort_order: 7,
        target_kcal: 200,
        target_protein: 0,
        target_carbs: 0,
        target_fat: 0,
        foods: [
          { name: 'Free Calories', qty: 1, unit: 'Qty', kcal: 200, protein: 0, carbs: 0, fat: 0 },
        ],
      },
    ],
  },
]
